### ISSUE TITLE
Upgrade guide

### ISSUE THREAD

**Issue by michaelGregoire** [ci-bonfire/Sprint#105]
The documentation should also contain upgrade instructions.

Oh... and thank you for what looks like it will be quite useful!

**Comment by lonnieezell** [comment]
Upgrade from what? This is a not-quite 1.0 version of a product.

**Comment by michaelGregoire** [comment]
I understand that... but it is at beta 1. So there should be a guide to make clear what files need to be upgraded when updating the install. I'm not going to use this for any project until I have a clear understanding of what will need to be updated when the next beta or v1 is released. If this were setup so that everything is in composer's vendor directory, it would be immediately apparent, but the way it's currently structured, it really isn't.

**Comment by lonnieezell** [comment]
Ah gotcha. Yes, when a beta2 (or 1.0 final) arrives, there will be a changelog and upgrade guide. 

The way it's structured, though, almost nothing in the application folder is touched at all by Sprint, which means don't touch the `myth` folder and you will be fine. :)

**Comment by michaelGregoire** [comment]
Ok, thanks for the info.
