### ISSUE TITLE
ThemedController, function e() refactor rename proposal.

### ISSUE THREAD

**Issue by dbrkv** [ci-bonfire/Sprint#107]
As proposal:
What if declarate `function e()` as method of `ThemedController` class?
I want to use Illuminate DB with sprint, but it have own `function e()`. I renamed `e()` to `e_myth()`, but better `$this->e()` I guess.Composer packages loaded by first and there is a problem.
What do you think about it?

**Comment by lonnieezell** [comment]
I can see that being a problem, as I have seen other packages out there using it so I renamed it to `esc`. I did not want to make a part of the themer or ThemedController because it needed to be available to use in the views themselves as a standalone method.

**Comment by dbrkv** [comment]
Ok, `esc` should be good.
Thanks!

**Comment by vinalask3** [comment]
I think same goes for the function dd(). I have resulted to using Kint::dump() just to ensure I am using the Sprint version of dd() and not Laravel's.
