### ISSUE TITLE
Registration email not being sent out

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#115]
I've installed a fresh copy of Sprint and for some reason the registration emails are no longer being sent out. I've configured auth.activation_method to email but I'm not getting anything. Is anyone else having the same problem?

**Comment by ronvillalon** [comment]
Just realized I didn't change the default mail service to CIMailService. Please disregard.

However, now I seem to be getting this weird result when the emails are being sent. Am I not configuring something correctly?

![email issue](http://snag.gy/TiXlO.jpg)

**Comment by lonnieezell** [comment]
Oops! Looks like I had left some debugging code in there. I'll remove it here shortly, but remove line 72 of CIMailService.php. 

```
die($this->ci->email->print_debugger() );
```

**Comment by ronvillalon** [comment]
Awesome
