### ISSUE TITLE
Password strength checking breaks with special characters because of GET

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#116]
![password strength checking error](http://snag.gy/wQsw0.jpg)

**Comment by ronvillalon** [comment]
I resolved this issue by double encoding the string right before it gets sent off to the server for processing. I do a base64 encode then a URL encode. On the server-end, I decode by running a URL decode then a base64 decode.

**Comment by shpeilin** [comment]
I'd like to share my code but personally I think the method should be switched to a POST. In fact, passwords and GET don't mix well at all. I'm going to assume the form will be served via SSL but I still think it should be sent as a POST.

**Comment by ronvillalon** [comment]
I made a mistake with my proposed solution--this is actually not a secure way of solving the problem. Use of GET will preserve parameters in browser history (along with someone's password even though it's encoded). This should be changed to POST. We can also remove double encoding once we use POST. What do you guys think?

**Comment by lonnieezell** [comment]
I have changed it to be a POST query in the commit just prior to this one. 

However, I thought that the double-encoding was simply to ensure no strange characters? Now that I say that, though, you're right - double-encoding isn't necessary since it's a POST request now. Good point. :)

**Comment by lonnieezell** [comment]
I've reverted that change now.

**Comment by ronvillalon** [comment]
Perfect!

**Comment by ronvillalon** [comment]
1. I re-reviewed the register.php and the password_check method in the Auth controller. Code was switched from GET to POST but I don't think we're actually using POST correctly. The password is still being sent via the URL. I think we need to switch to making it as POST data.
2. If I enable csrf_protection = TRUE within config.php I receive a 403 error.
