### ISSUE TITLE
testGetPost() in /Sprint/tests/unit/CITest.php fails

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#120]
I'm a bit confused on why there's an exclamation mark in the code snippet below if we're trying to make sure testing passes. Am I missing something or should that be removed?

`Line 12 of /Sprint/tests/unit/CITest.php`

```
$this->assertEquals(! $expected, $this->ci->input->get_post('foo'));
```

**Comment by lonnieezell** [comment]
My apologies - that test should have never made it into the repo. I was testing some things based on another issue raised here, and had to check both success and fail states of the test. I'll remove that class now. Thanks for pointing it out.
