### ISSUE TITLE
Undefined esc() function

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#122]
> If you have specific data that you want to escape within your view, you can use the esc() function, which is the same function that is used by the ThemedController to handle the escaping.

If you try to use this function in a view file, you'll get an undefined esc() function error.

**Comment by lonnieezell** [comment]
Fixed in: 9276f3fcbe60883ea3b3e8f26f0600d3da88a05f but I forgot to tag it in the commit message.
