### ISSUE TITLE
Error while creating Module through forge

### ISSUE THREAD

**Issue by ghost** [ci-bonfire/Sprint#123]
Severity: Warning
Message: mkdir(): Invalid argument
Filename: myth\Forge\BaseGenerator.php

**Comment by lonnieezell** [comment]
Sorry it's taken so long to get to this. Can you provide more details about how you got that error and what your system environment is like?

I just successfully ran through `sprint forge scaffold` and answered the questions along the way without an issue. Did you possibly miss answering one of the prompts?

**Comment by ronvillalon** [comment]
I think I received this error before. Did you properly set up your permissions? See [Folder Permissions](https://github.com/ci-bonfire/Sprint/blob/develop/myth/_docs_src/installation.md)

**Comment by ghost** [comment]
Hi, i got this error while creating the module but works properly if i use scaffold command

![error](https://cloud.githubusercontent.com/assets/3718339/9133130/b64a2388-3d16-11e5-9616-b12172dd7d71.png)

**Comment by andvenaa** [comment]
I also got this problem in windows. Found a quickfix to get it working.

Change sandbox function in BaseGenerator.php and add a new function 

```
    public function sandbox($path)
    {
         $path = $this->normalizePath($path);
        // If it's writing to BASEPATH - FIX IT
        if (strpos($path, $this->normalizePath(BASEPATH)) === 0)
        {
            return APPPATH . $path;
        }

        // Exact match for FCPATH?
        if (strpos($path, $this->normalizePath(FCPATH)) === 0)
        {
            return $path;
        }

        // Exact match for APPPATH?
        if (strpos($path, $this->normalizePath(APPPATH)) === 0)
        {
            return $path;
        }

        return APPPATH . $path;
    }

// From php.net http://php.net/manual/en/function.realpath.php
public function normalizePath($path)
{
    $parts = array();// Array to build a new path from the good parts
    $path = str_replace('\\', '/', $path);// Replace backslashes with forwardslashes
    $path = preg_replace('/\/+/', '/', $path);// Combine multiple slashes into a single slash
    $segments = explode('/', $path);// Collect path segments
    $test = '';// Initialize testing variable
    foreach($segments as $segment)
    {
        if($segment != '.')
        {
            $test = array_pop($parts);
            if(is_null($test))
                $parts[] = $segment;
            else if($segment == '..')
            {
                if($test == '..')
                    $parts[] = $test;

                if($test == '..' || $test == '')
                    $parts[] = $segment;
            }
            else
            {
                $parts[] = $test;
                $parts[] = $segment;
            }
        }
    }
    return implode('/', $parts);
}
```

This is just a quickfix so i can use the forge command. The problem is the path part that is different on windows and nix.

**Comment by lonnieezell** [comment]
@andvenaa That sounds like a pretty good solution, though I would have thought that the BASEPATH, APPPATH, etc would have been fine since some of that is taken care of nicely in the index.php file. 

I'm fine with this solution, though, and will get a commit for it tonight. Thanks!
