### ISSUE TITLE
[Auth] Login attempts issue

### ISSUE THREAD

**Issue by michalsn** [ci-bonfire/Sprint#150]
Documentation says that developers can use different fields during login process (default email and username) but in practice using any different field than `email` creates a security vulnerability, because we use `recordLoginAttempt` method only when email is used. So distributed bruce force attack based on username field could be not detected.

The best solution IMO would be to require to choose between email and username (or whatever else we want to use) in config file (let say the default value would be an email). So basicaly we would resign from `auth.valid_fields` config value and replace it with something like `auth.auth_field` (same as in BasicAPIAuthentication). Then in `auth_login_attempts` table we could rename `email` field, to `identity` and record login attempts for chosen value in config.

What do you think about it?
Does option to authenticate by many fields is really a "must have"?

**Comment by lonnieezell** [comment]
The primary reason that I included authenticate by many fields is for those sites that want to use "Email or Username", which is more convenient for the user. Also less pages for the developer to create for "Forgot Username?".. maybe just one less. :) But no, it's not a must have. 

LocalAuthentication does assume that all users have email addresses, which might be a bad assumption. However, here are the types of places I could see non-standard logins being used. Some of which might or might not have emails associated with them, though I think that most would:
- Public schools often have systems where students log in via student ID.
- Intranets might use employee ID's, though more likely emails
- I see a lot of systems, generally attached to Point of Sale systems, use an employee ID

Those are the ones that come to top of mind. My only concern would be that you would also have IT staff, admins, or owners that would need to login via more secure credentials. And that is where I think the ability to provide more than one field can come in handy.

I like your idea if we don't need to support multiple. My biggest argument against what I just put out there is that for better security, they should develop those systems as separate apps, anyway. 

So, I might have convinced myself that we should go that route. :)

**Comment by michalsn** [comment]
Haha - now I'm not convinced :)
The cases you have mentioned are really valid points... I didn't think about it earlier.

I came up with solution that may be the good choice for authentication by many fields.
We have to change table structure for `auth_login_attempts` a little, to introduce types of login attempts:
- `app` - log all failed attempts
- `ip` - log all failed attempts by IP address
- `user` - log all failed attempts by user ID

Entries for `app` type are never deleted, so we have always full log history to use with `distributedBruteForceTime` method. We are able to set ban for users based on IP address or user ID - rules are the same as before. And last but not least we're independent from field used during login.

Please, take a look at this when you will have some time :)

**Comment by lonnieezell** [comment]
I like what you've done, and think it's a good all around solution. The one issue I have is that I think we need to use `$this->input->ip_address()` to grab the ip address everywhere. For simple web apps, I don't see much benefit to it, but for more highly-trafficked apps, that method respects proxy servers that have been setup so we don't end up throttling because the IP is the proxy that all requests are being routed through. 

If you can update that, I'll be happy to merge. Thanks!

Of course, using the input lib is just one more thing I'll have to create a work around whenever I get time to separate the Auth from CI to make it framework agnostic, but that's the best solution for now, I believe.

**Comment by michalsn** [comment]
Done.

**Comment by lonnieezell** [comment]
Awesome. Thanks! And merged.
