### ISSUE TITLE
Views path for scaffold created in modules

### ISSUE THREAD

**Issue by juju95** [ci-bonfire/Sprint#16]
Hi, just to let you know, when we create a scaffold in a module, for example : 

php index.php forge scaffold mywantedname -module mymodule

the views are in /mymodule/views/viewname.php

but the controller expect them to in in /mymodule/views/mywantedname/viewname.php

there will be a problem if we create 2 scaffolds in the same module directory

**Comment by juju95** [comment]
I corrected it replacing the $subfolder line on ControllerGenerator.php line 176 by 

$subfolder = '/' . $data['lower_name'];

**Comment by lonnieezell** [comment]
Sorry - just getting back from Christmas break. I'll take a look at this, but should be a simple fix, as you've described. Just want to make sure that no edge cases can be thought of.

Pull requests are always welcome. :)
