### ISSUE TITLE
 No data is displayed in the edit screen.

### ISSUE THREAD

**Issue by youheinakagawa** [ci-bonfire/Sprint#162]
Hello,

This generated 'view' file has been used is 'object'.
https://github.com/ci-bonfire/Sprint/blob/develop/myth/_generators/Controller/view_update.tpl.php#L25

This generated 'model' file has been used is 'array'.
https://github.com/ci-bonfire/Sprint/blob/develop/myth/_generators/Model/model.tpl.php#L81

It can not display data to the generated 'view' file.

May I edit the 'model.tpl.php' file?

**Comment by lonnieezell** [comment]
Yes, you can absolutely do that. You can also create custom generators to create things exactly like you need it for your projects, if you wish. 

That's a good catch, though, and I need to get that fixed up. I'll do a temporary fix to make them match, but I'll need to go further and see if they can get smarter.

**Comment by lonnieezell** [comment]
Modified the model generator in 1ef776667cb429f8cc4f458b0002de39392182d7 because I think arrays are much more usable as a default. You are always free to update your personal ones as you see fit, though.
