### ISSUE TITLE
Class User_model already exists and doesn't extend CI_Model

### ISSUE THREAD

**Issue by italo1983** [ci-bonfire/Sprint#176]
Can't make the hasPermission method to work, when user has selected permission CI return this error: Class User_model already exists and doesn't extend CI_Model.

$this->setupAuthClasses();
$user_id = $this->authenticate->id();
echo $this->authorize->hasPermission('backend.dashboard', $user_id);

**Comment by italo1983** [comment]
I've founded the problem, when a user has no groups the authorize class fail with this error. Problem solved.

**Comment by lonnieezell** [comment]
Glad you found the issue! And thanks for letting me know what it was.

**Comment by ghost** [comment]
or the name of your controller and model are the same, make sure it's different.
**my problem solving**
