### ISSUE TITLE
download failure

### ISSUE THREAD

**Issue by jzdexta** [ci-bonfire/Sprint#180]
Hi trying to download via composer and getting below error

Content-Length mismatch, received 357437 bytes out of the expected 357633
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

                                                                               
  [Composer\Downloader\TransportException]                                     
  The "https://packagist.org/p/provider-2017-10%2421853423c79338be8ce4a924e81  
  fd35df418bb355f9ee81ab6c9333f7fc137e0.json" file could not be downloaded (H  
  TTP/1.1 404 Not Found) 

What could be the problem.

Thanks in advance

**Comment by lonnieezell** [comment]
That's a good question. Sounds like a Composer issue, though, or a glitch on packagist maybe. Shouldn't be Sprint related.
