### ISSUE TITLE
Disable /docs

### ISSUE THREAD

**Issue by hnnweb** [ci-bonfire/Sprint#53]
How do i disable the /docs route?

Best of all would be if it can be disable depending on the environment constant.

**Comment by lonnieezell** [comment]
You're in luck! :) 

Edit `myth/CIModules/docs/config/docs.php`, down at the very bottom: 

```
$config['docs.permitted_environments'] = array('development', 'testing', 'production');
```

Make sure that includes only the environments that you want docs to work in and it should disable them. 

Alternatively, you could edit the routes file, something like: 

```
if (ENVIRONMENT != 'develop') 
{
    $route->block('docs(.+)');
}
```
