### ISSUE TITLE
CIDbModel observers vs as_array()

### ISSUE THREAD

**Issue by dbrkv** [ci-bonfire/Sprint#67]
I perform db action:

```
$this->model_name->as_array()->find_all()
```

And my observer hook **after_find** fired, but $data array have (array) format also. Data manipulation in my **after_find** uses object oriented way to work with array, but as_array() return standart array, so no any modifications in **after_find** action happens.
Bug or proposal to enlargement?

**Comment by lonnieezell** [comment]
Since you specified the as_array()  and wrote the after_find observer it should be pretty simple to modify, right? :) 

The best way to do that would be to check the type of object you got and get/set the data accordingly, so that it can work with either type.

**Comment by dbrkv** [comment]
Yes, I have already refused to use as_array()
Need to keep one style to work with arrays... I'm a little tired and not pay attention on it:)
Thanks!
