### ISSUE TITLE
CLI Generator: Class Session not found

### ISSUE THREAD

**Issue by vinalask3** [ci-bonfire/Sprint#68]
![sprint_cli](https://cloud.githubusercontent.com/assets/2475629/6802882/1c0f60e6-d234-11e4-94d7-0af29163819b.png)
![sprint_cli2](https://cloud.githubusercontent.com/assets/2475629/6802927/813d9988-d234-11e4-98ee-bc44360f6ffd.png)

**Comment by lonnieezell** [comment]
Thought I had resolved that a while ago, but will check into it. In the meantime, if you set the Session class to be auto-loaded I believe that will get you running for now.

**Comment by vinalask3** [comment]
The session class is autoloaded already.

**Comment by lonnieezell** [comment]
Ah - a quick test shows that removing session from the autoload fixes things. Not sure what's going on but that should get you running until I have more time to look into it.
