### ISSUE TITLE
Detect two-character segments as a localize string

### ISSUE THREAD

**Issue by lonnieezell** [ci-bonfire/Sprint#69]
This has a few needs: 
- Config item in application.php to turn on localization support
- Config item in application.php that's an array of supported language strings that will be detected and are supported by the application. All other languages are ignored.
- Should be able to use MY_URI and check segment[0] in the constructor and compare against the languages we're using.
- Must be able to convert the two-character ISO language code to match with the available [CodeIgniter translations](https://github.com/bcit-ci/codeigniter3-translations).
- should define a constant, LANGUAGE, with the appropriate translation string. 
- If the first segment is determined to be a valid language, it should be removed the segments returned in all uri_string and segment() methods. This should be as simple as shifting it off the top of the segments array, but this needs to be ensured. 

Please provide tests.

NOTE: We will NOT redirect the user or anything else based upon the language at this time. That should be left up to the application dev to determine how they want to handle that. 

[Interesting Reading](http://www.w3.org/International/questions/qa-accept-lang-locales)

**Comment by IrcDirk** [comment]
"should define a constant, LANGUAGE, with the appropriate translation string" where this should be? In MY_URI?

**Comment by lonnieezell** [comment]
Wherever is most logical. Obviously, the URI class will be responsible for determining whether that is a language string or not, so it would make sense that it either defines the constant there (it will run very early in the bootstrap process) or load a new `i18n` class to do the dirty work. 

And that's probably the proper way to do it there - create a new `Myth\Localization\i18n` class that will do that actual language detection and determining the language mapping between 2-character ISO codes and the translation name. We can then use that namespace to add in features as we go along.

**Comment by IrcDirk** [comment]
Ok first pull request https://github.com/ci-bonfire/Sprint/pull/74 should cover all this thread needs.

**Comment by IrcDirk** [comment]
One thing that is left is to add doc for i18n config/application.php items. My english isnt so good so maybe ill leave it to you.

**Comment by lonnieezell** [comment]
Thanks so much! 

I've done a touch of refactoring. I was getting some errors on my machine so that's part of the reason. Additionally, I realized that we were loading the i18n class even if we didn't need it, so I moved the check against the config item to the MY_URI class. 

Also, the I18n class will be simpler to test if it takes the segments and then returns them, without doing anything magical in the background, like the array_shift on the original object.

I'll work up docs for this feature, and put some tests together later tonight.

**Comment by IrcDirk** [comment]
Ohhh well, good catch with moving `i18n` check to MY_URI class.

As for working with pointer to segments array that just was simpler for me, but sure it can be problematic sometimes.

**Comment by lonnieezell** [comment]
I agree it's simpler - but makes testing a pain. :) That's the only reason I changed it.

**Comment by IrcDirk** [comment]
Didnt know that... thas why i have to dig into unit testing.

**Comment by lonnieezell** [comment]
I've got basic tests in place, and had to refactor and expand what you were working on. It was having issues with some of the URI commands, since array_shift would reset the array indexes to a zero-based array, instead of the 1-based array it was needing. I played around with a few different solutions and ended up with something that feels a bit hacky but works. Wish I could have found something more elegant. :)

Also had to create a new method to keep the uri_string functions working. 

I didn't test the ruri\* methods but they should be fine. At the point that the class is loaded and i18n fired up, the ruri_segments is empty since the router hasn't run and set those yet. 

I'll close this for now, but feel free to comment or reopen if needed.

**Comment by IrcDirk** [comment]
Wouldnt it be better to use:

```
$segments = array_values($segments); // resets all segments, now index starts at 0 (index 1 is now index 0, and so on...)
unset(segments[0]); // remove segment 0 with 2-character lang ISO
```

instead of `array_walk` with callback? 

Certainly it is faster (did some testing) and more clear to the code.

**Comment by lonnieezell** [comment]
I'm sure it is faster. That's not one of the variations I tried last night, but if it works, I'm fine with it. I'm afraid that it's going to return a zero-based array, though, which will break the URI commands. 

Though I read your code again and it does an unset after. If that will pass all of the tests, and I think it should, then that's cool. I'm always one for simplicity and performance.

**Comment by IrcDirk** [comment]
Nope, `unset` removes item from array without reindexing. Reindexing to zero index with `array_values` will make segments look like `[0 => 'en', 1 => 'home']` then `unset` will just left `[1 => home]`. Test it.

**Comment by lonnieezell** [comment]
Yeah, I know unset does. That's why I said it looked like it should work. I just didn't think of that way last night, so as long as it passes the unit tests, I'm good with it being changed.

**Comment by IrcDirk** [comment]
I didnt saw the edited comment. I think i was writing mine when u were editing yours... So im waiting for test results becouse im courious if it will work fine.
