### ISSUE TITLE
Loggedin session not found

### ISSUE THREAD

**Issue by nhymxu** [ci-bonfire/Sprint#73]
I check Login action. After login, topbar alway show "Login" text (click this and auto redirect to current page)

but in topbar.php, I see

```
<?php if (!empty($_SESSION['logged_in']) ) : ?>
```

try var_dump($_SESSION); and return null

**Comment by lonnieezell** [comment]
My apologies. When I had that working a few days ago I had autoloaded the session library, but that ended up causing issues with the command line tools. 

You just need to ensure the session library is loaded. I will add that to the BaseController for now.

**Comment by lonnieezell** [comment]
Fixed and committed.
