### ISSUE TITLE
Provide database options setting for migrations

### ISSUE THREAD

**Issue by lonnieezell** [ci-bonfire/Sprint#76]
Problem: Migrations don't assume any particular table type, etc when creating new tables. To help users make settings like default table type = InnoDB or encoding, etc, we need to make it simple for them to add those default settings.

Solution: Since we can pass an [$attributes array](http://www.codeigniter.com/userguide3/database/forge.html#creating-a-table) in as the third parameter of the create_table method, we should provide a new config setting that is an empty array by default but will be creating by any migration generators, and that is in the basic generators.

**Comment by IrcDirk** [comment]
This configuration item, sould i add to config/migration.php or config/application.php?

**Comment by lonnieezell** [comment]
Good question. I guess migration is the more logical place since it will always be used within migrations.

**Comment by IrcDirk** [comment]
I've added config item `migration_create_table_attr` to config/migrations.php and i could modify templates like this:

`$up .="    \$this->dbforge->create_table('{$table}', \$this->_migration_create_table_attr);`

Couse else i have to extend forge lib to change `create_table` function to implement `migration_create_table_attr` setting.... i dont see other solution...

**Comment by lonnieezell** [comment]
`create_table` already [accepts an arguments array](http://www.codeigniter.com/userguide3/database/forge.html#creating-a-table) as the third attribute. 

We can just use that. I thought's that what we were doing anyway, aren't we? 

I would just use TRUE as the second parameter and it should all be good. Or am I missing something?

**Comment by IrcDirk** [comment]
We are generating files from templates so i have to edit .tpl files and change:

`$up .=" \$this->dbforge->create_table('{$table}')`

to

`$up .=" \$this->dbforge->create_table('{$table}', \$this->_migration_create_table_attr)`

couse this is the way we are sending arguments array.

But we can leave templates alone and change native forge `create_function`:
- check if argumets array is empty
- then check if `migration_create_table_attr` is set
- if yes then set argumets array to `migration_create_table_attr`

**Comment by IrcDirk** [comment]
Or change BaseGenerator.php function `render` to str_replace:

`create_table('{$table}')`

to

`create_table('{$table}', true, \$this->_migration_create_table_attr)`

if `migration_create_table_attr` is set?

**Comment by lonnieezell** [comment]
I'd rather not override another core class if we don't have to. It seems easier to override the `.tpl` files to be: 

`$up .=" \$this->dbforge->create_table('{$table}', true, \$this->_migration_create_table_attr)`

All that needs to be added is the `true` as the second param there so it will go ahead and add `IF NOT EXISTS`. 

While I agree that it might be convenient to override a single method in dbforge:

a) I don't want to interfere with anyone else's customizations (which, granted, is probably pretty slim chance of that being a problem)
b) don't want to have to deal with any changes CI might make in the future
c) This is really only something for Sprint so truly only applies to migrations we make. If someone is using the Forge to create a migration, that code will be generated for them. If not, then they should be able to write the code like they need it in the first place, and could even pull in our config item if needed.

**Comment by IrcDirk** [comment]
What about the secound sollution with `str_replace`?

**Comment by lonnieezell** [comment]
Tempting, but could only be "guaranteed" to work for our own templates. 

When a user makes a custom collection they could easily have different spacing in the string, etc. They also make have different needs we haven't thought of yet. 

Least error prone and future proof seems to be to just modify our own templates.

**Comment by IrcDirk** [comment]
Ok, so ill do it with tpl change.

**Comment by eincandela** [comment]
Did you implement the migration_create_table_attr already ? i cannot find it in code

**Comment by IrcDirk** [comment]
Not yet. Will do in spare time.

**Comment by lonnieezell** [comment]
I just pushed a fix for that.
