### ISSUE TITLE
Logout message not displaying

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#81]
Hello,

Is it just me or is the logout message not showing up? Using session_destroy() (LocalAuthentication) and then immediately calling setMessage() (in Auth logout method) won't work as designed. The flashdata in setMessage will disappear because it's being called within the same request.

Re: session_destroy() from CodeIgniter docs:

This must be the last session-related operation that you do during the same request. All session data (including flashdata and tempdata) will be destroyed permanently and functions will be unusable during the same request after you destroy the session.

-shpeilin

**Comment by lonnieezell** [comment]
Oh, you are correct. I can't remember if that ever worked, to be honest, but you're right - there's no way that it should be able to. 

I'll set it to start up a fresh session after destroying it so that the flash messages and the like can still be displayed.

**Comment by lonnieezell** [comment]
Actually, I simply ensured that all data was deleted from the session instead of completely destroying it. This gets rid of any potential security holes that I can think of and still maintains the objective here.

**Comment by ronvillalon** [comment]
Hi again,

To be on the safe side, would it make sense security-wise to regenerate the session ID after you empty session data? I would add $this->ci->session->sess_regenerate(); right after your modified code.

Similarly, I would regenerate the session ID right before the user is logged in--just before the following code: $this->ci->session->set_userdata('logged_in', $user['id']); in loginUser().

... this was my interpretation of the following readings:
https://www.owasp.org/index.php/Testing_for_Logout_and_Browser_Cache_Management_(OWASP-AT-007)
https://www.owasp.org/index.php/Testing_for_Session_Fixation_(OWASP-SM-003)

-shpeilin

**Comment by lonnieezell** [comment]
That's a good point. Definitely couldn't hurt. Reading the first article made me realize that we should be sure that no-cache header is sent if the user is logged in also. 

So - I'll read through those articles some more and see what I missed. Thanks!

**Comment by lonnieezell** [comment]
I think these last few changes should help defeat the vast majority of issues you were seeing, with a couple of tiny defaults provided in the config file for new projects also. 

Let me know if you think I missed anything. 

And thanks for reporting.

**Comment by ronvillalon** [comment]
Great--I think the no-cache header would be a great addition. It's especially important for pages with PII, CC data, etc.

As I continue to look through Sprint's security features, I will let you know if I find anything else.

-shpeilin

**Comment by lonnieezell** [comment]
I actually added to no-cache headers whenever someone is logged in with the previous commit so we are, hopefully, good to go.

Closing this but feel free to open a new one if you find anything else.
