### ISSUE TITLE
Email Encoding

### ISSUE THREAD

**Issue by eincandela** [ci-bonfire/Sprint#82]
Hello,

i've searched through the code and doc but i cannot manage to have sprint send HTML email. 
It seems the header are not send correctly. The html code is displayed in the  emails as  plain text. 
i even tried to force HTML format in CIMailService..

I hope i didn't miss a simple config item...gasp... :)

**Comment by lonnieezell** [comment]
I jus tested and you're right! Interesting. It works with the LogMailer but not with CIMailer. I'll dig into it tonight and see if I can find the cause. 

Thanks for reporting.

**Comment by lonnieezell** [comment]
Found and fixed.

**Comment by eincandela** [comment]
you're welcome ! and btw you are my very first github report ! ahah
