### ISSUE TITLE
myth/Forensics/views/profiler_template.php is not used...

### ISSUE THREAD

**Issue by IrcDirk** [ci-bonfire/Sprint#85]
`profiler_template.php` is used from `APPATH/views` but not from `myth/Forensics/views/profiler_template.php` should this work or this file is not used?

**Comment by lonnieezell** [comment]
That's correct, it's not. I could take it out, but it makes a nice backup in case anyone truly messes with the view or accidentally deletes it, etc. Leaving in for now.
