### ISSUE TITLE
Sprint Model's observer does not always return an id, method, and fields

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#88]
Hello,

In Sprint Model's documentation, it mentions that the first parameter for the callback method will have the following: id, method, and fields. However, it seems that these variables are only returned for the after_insert and after_update observers. Am I missing something here or were they intended to be for those two observers only and the documentation needs updating?

Thank you.

-shpeilin

**Comment by IrcDirk** [comment]
Hmmm... this are callbacks methods so they returns whatever u decide to return:

https://github.com/ci-bonfire/Sprint/blob/develop/myth/Models/CIDbModel.php#L1324

**Comment by mwhitneysdsu** [comment]
Any method used for an observer should have a consistent return type/value, so it's important that it is documented correctly AND that anyone implementing a method to be called by the observer return the documented type/value (and accept the documented inputs).

In most cases, you simply return whatever data was passed in to the method. In this case, I think @shpeilin may be concerned that the input does not contain the expected data, which can make it difficult to write a callback method for the observer. For example:
- before_find receives no data
- after_find receives a row of data in the current return type (array or object; if the final output of find() should be json, the json encoding is performed after the observer is called). In find_all(), a third parameter (the row number) is sent to trigger() for 'after_find', but trigger doesn't appear to accept/use the third parameter.
- before_insert receives the validated data
- after_insert receives an array: ['id' => $id, 'fields' => $data, 'method' => 'insert']; insert_batch() does not trigger after_insert; replace() triggers after_insert with the same array, but 'method' is set to 'replace'
- before_update receives $data (with [$this->primary_key => $id] merged into it in update(), but not in other methods); update() also passes $skip_validation as a third parameter to trigger(), though, as mentioned before, trigger() doesn't accept/use the third parameter.
- after_update receives ['id' => $id, 'fields' => $data, 'result' => $result, 'method' => 'update']; in update_batch(), after_update is triggered for each row with the same array, except the 'id' field is not included and 'method' is set to 'update_batch'; update_many() triggers after_update once, with 'id' set to $ids (an array of primary_key values) and 'method' set to 'update_many'; update_by() and update_all() trigger it with array($data, $result)
- before_delete receives $id from delete(), $where from delete_by(), and $ids from delete_many()
- after_delete receives $result

**Comment by lonnieezell** [comment]
You're right - I think I had started to go back through and expand what each one was providing to make them more consistent, where possible, but got sidetracked and never came back. 

I'll work on that some today, since I have a little spare time, and upgrade the docs for that for sure.

**Comment by ronvillalon** [comment]
Commit looks good. Adding the method for each observer makes this feature much more useful. For example, callback methods can be customized accordingly much more easily now that we can determine if find_all was called vs find_by. Thanks.

**Comment by IrcDirk** [comment]
@lonnieezell u have problems with this commit https://github.com/ci-bonfire/Sprint/commit/09a4c30a8203f44040fb7ba5e3d50ee84662e090 

Travis reports build problems: https://travis-ci.org/ci-bonfire/Sprint/builds/58546033

**Comment by lonnieezell** [comment]
I know. It emails me. In this case it's the tests have to be modified to show the proper expectations. Was too tired to fix last night but will do so today.

**Comment by IrcDirk** [comment]
No problem, just thought u missed this report.

**Comment by lonnieezell** [comment]
It was actually a touch more than that, but just got it fixed. Thanks.

**Comment by IrcDirk** [comment]
Since u made this changes u need to update `User_model` becouse `hashPassword($data)` now gets different data. May there be more functions that have to be updated in other models?

**Comment by lonnieezell** [comment]
Yeah I got a message on the forums about that. :( guess I didn't think of that the other day. And obviously don't have any tests on that... So I'll take care of that tomorrow night.
