### ISSUE TITLE
404 Not Found issue with controllers placed in subdirectories within subdirectories

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#89]
Hello,

Been getting 404 Not Found for controllers placed within deep subdirectories. For example, the following file will issue a 404 Not Found:

/application/controllers/admin/setup/timezones.php

Anyone else getting this issue?

-shpeilin

**Comment by lonnieezell** [comment]
I found the issue and corrected it (for the main controllers folder only). The HMVC solution that is bundled with Sprint was written before CI3 came out, but was fairly trivial to update. However, I had forgotten that CI3 supported unlimited nesting of folders within controllers now. 

This has been remedied. Thanks for reporting it!

**Comment by ronvillalon** [comment]
Great--thanks for the fix.

-shpeilin
