### ISSUE TITLE
Error on database install 

### ISSUE THREAD

**Issue by eincandela** [ci-bonfire/Sprint#92]
When migrating the database on install, i have an error on "settings" table creation.

The forge command trying to create the key('name_group') raise a mysql error "Specified key was too long; max length is 1000 bytes"

My mysql version is 5.6.15-log on windows

some more infos i picked on google:
"
The best practice is to use prefix indexes so you're only indexing a left substring of the data. Most of your data will be a lot shorter than 255 characters anyway.
You can declare a prefix length per column as you define the index. For example:
...
KEY `index` (`parent_menu_id`,`menu_link`(50),`plugin`(50),`alias`(50))
"

but i don't know how to do that in Forge.

**Comment by IrcDirk** [comment]
This is related to: https://github.com/ci-bonfire/Sprint/issues/76. You should set your database and tables to InnoDB, then it will work.

**Comment by lonnieezell** [comment]
I believe this was solved in two ways. The most likely case is that it was using the entire set of columns to create an index out of since no primary key existed on that. With the blob data field it would definitely show up as too long. This was converted to primary keys in #91. 

Additionally, I pushed the change so that you can set additional attributes during table creation for #76. 

Should be resolved now. Closing.

**Comment by eincandela** [comment]
it seems the config array item is not available to the migrations script, so a NULL value is send to the create_table as the third parameter and it crashes

**Comment by lonnieezell** [comment]
That's strange. I ran it through with and without any items in the array, and didn't hit any errors in a stock sprint install. And the migration config file is loaded in the constructor of the migration file so it should be always available. 

When, exactly, are you seeing this?

**Comment by eincandela** [comment]
well..strange..it was in a windows command console but now it works fluently..sorry for false reporting..i must have touched something

**Comment by lonnieezell** [comment]
No worries. Just glad it's working. That didn't sound like it was going to be a fun one to track down. :)
