### ISSUE TITLE
CIDbModel created_by, modified_by not updated

### ISSUE THREAD

**Issue by IrcDirk** [ci-bonfire/Sprint#95]
CIDbModel `created_by`, `modified_by` are not updated by events.

**Comment by dbrkv** [comment]
`deleted_by` too.

**Comment by IrcDirk** [comment]
`deleted_by` should work: 

https://github.com/ci-bonfire/Sprint/blob/develop/myth/Models/CIDbModel.php#L866
https://github.com/ci-bonfire/Sprint/blob/develop/myth/Models/CIDbModel.php#L889
https://github.com/ci-bonfire/Sprint/blob/develop/myth/Models/CIDbModel.php#L912

soft deletes must be enabled to make this work.

**Comment by lonnieezell** [comment]
And you have set_created and set_modified to true in your model?

**Comment by dbrkv** [comment]
But not. 
Soft deletes enabled, when `$log_user = TRUE`

I got:

```
Severity: Notice
Message: Undefined property: Admin::$auth
```

Can you confirm?

Also I noticed that
https://github.com/ci-bonfire/Sprint/blob/develop/myth/Models/CIDbModel.php#L321
Tries to assign value to protected member

**Comment by IrcDirk** [comment]
@lonnieezell yes i have it enabled, `created_on`, `modified_on` works but not `created_by`, `modified_by`.

@namemsile as for line L321 it may work for hmvc models but might not work for normal and also this fix does not fixes isse with callbacks from autoloaded models from BaseController https://github.com/ci-bonfire/Sprint/pull/94#issuecomment-95478614 :/ Ill will check this today...

**Comment by lonnieezell** [comment]
Sorry - read the fields wrong. 

For the auth issue - that appears to be a holdover from Bonfire that I didn't catch. Trying to think of a nice, clean, non-auth-library dependent way to handle that and the only thing I'm coming up with is a new method `setUserId()` or to accept the user id as a parameter to any method that might need it. Maybe adding both would make sense. 

And you're right that it looks like created_by and modified_by was not implemented. Since the project I'm working on is using that feature, I'm sure I would have noticed in the next day or two but looks like you guys beat me to it. :)

**Comment by IrcDirk** [comment]
Or we can check if auth-library is loaded? If not then force `log_user = false` and add documentation about auth-library dependency?

**Comment by dbrkv** [comment]
if change `$this->auth->user_id()` to `$this->authenticate->id()` field `deleted_by` filled by user id

https://github.com/namemsile/Sprint/blob/develop/myth/Models/CIDbModel.php#L866

**Comment by lonnieezell** [comment]
I'm honestly not sure how `$this->authenticate` is even available within the model. Must still be early here. :) 

If you look at the AuthTrait, then it loads a class_var called 'authenticate' with the authentication library. That's a class var for the controller, and shouldn't be part of the CI singleton. So I don't think we can rely on that being there, or even rely on being able to tell if the auth class is loaded in a way that we have access to it...
https://github.com/namemsile/Sprint/blob/develop/myth/Auth/AuthTrait.php#L204

My brain's a little fuzzy at the moment. Let me investigate further.

**Comment by lonnieezell** [comment]
Ok. thanks to CI's get_instance being tied to the controller, we can check within the model to see if a class var is set in the controller. Very strange voodoo I always take for granted. :) 

So, it looks like we can rely on $this->authenticate being available. At least, as long as people are using the AuthTrait - and why wouldn't they be? :)

**Comment by dbrkv** [comment]
So, model's magic `__get()` fires `get_instance()->$key` and get's `$this->authenticate` which is must be setted in controller. Let it be:)

**Comment by lonnieezell** [comment]
Letting it be :) 

I just pushed some code that I believe fixes all of the issues in e6e9271a7713eef3667cddc9f32b47cc5a56ac61 but I don't want to close this until you guys have had a chance to test it out to be sure.

**Comment by dbrkv** [comment]
Hm. In model `$log_user = TRUE`, but in debugger `$this->log_user = FALSE`` because 

```
    if (empty($this->authenticate))
    {
            $this->log_user = false;
    }
```

`$this->authenticate` not already a property of model. This get's from magic methods.

**Comment by namemsile** [comment]
Also, ```$this->get_instance()``` does not works in constructor due to ```CIDbModel``` does not extends CI :(

**Comment by lonnieezell** [comment]
Well, `get_instance()` is part of the controller. The only thing the CI_Model file has is the magic `__get` which I've recreated. 

Alright, I'll move the check to the individual methods, then. Dang. Good catch, though.

**Comment by dbrkv** [comment]
I have some misspilled in $this->get_instance() and get_instance() but it does not make sence. In model's constructor get_instance()->authenticate = NULL, but it return an object instance in methods. Hm.

**Comment by lonnieezell** [comment]
Did you try the latest commit I just made a few minutes ago?

**Comment by dbrkv** [comment]
yes, just now.
`! empty()` need change to empty(), because empty() returns true.
I've tested modified_on() and deleted() methods.

**Comment by dbrkv** [comment]
I make checks for $this->authenticate:
- empty() returns TRUE
- is_null() returns FALSE
- isset() returns FALSE

Not sure, but maybe better use is_null() for $this->authenticate check?

**Comment by lonnieezell** [comment]
I'm thinking maybe ! is_object() but haven't done any testing yet. Trying to crank some paying work out currently and won't be able to back to it until later tonight.

**Comment by IrcDirk** [comment]
`is_object` should be ok in this case.

**Comment by dbrkv** [comment]
I think `! is_null()` or `$this->authenticate !== NULL` will be enough. Anyway `$this->authenticate` is an object instance, we just need to check for it assigned or not. But `is_object()` should work too.
