### ISSUE TITLE
CIDbModel return whole array from trigger if $row = null

### ISSUE THREAD

**Issue by dbrkv** [ci-bonfire/Sprint#99]
If no rows found by find(), $row = null, array `['id' => $id, 'method' => 'find', 'fields' => $row]` passed to trigger():

```
// skipped this, because $data['fields'] = NULL
if (isset($data['fields']))
{
    return $data['fields'];
}
```

and find() return to controller `array('method' => 'find', 'fields' => null)` from trigger() which is not handy to handle in controller.

**Comment by lonnieezell** [comment]
I'm away from computer this weekend but will gladly accept pull requests :)

**Comment by dbrkv** [comment]
@lonnieezell , https://github.com/ci-bonfire/Sprint/commit/7fb79d4f8c7bcba6c9c4117e33c21779107dbd11

**Comment by dbrkv** [comment]
Also:

```
        if ($this->temp_return_type == 'json') {
            $rows = json_encode($rows);
        }
```

will return null.
what do you think about:

```
        if ($this->temp_return_type == 'json') {
            $row = ! empty ($row) ? json_encode($row) : json_encode([]);
        }
```

**Comment by dbrkv** [comment]
or
`json_encode([])` for find_all()
and
`json_encode( (object) [])` for `find()` and `find_by()`

**Comment by dbrkv** [comment]
@lonnieezell, https://github.com/ci-bonfire/Sprint/pull/101
